"""intial migrate

Revision ID: 2dad29185a3d
Revises: 
Create Date: 2023-05-17 07:17:27.501035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dad29185a3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addproducts')
    op.drop_table('catagory')
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.alter_column('image1',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('image2',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('image3',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.alter_column('image3',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('image2',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('image1',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    op.create_table('catagory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('addproducts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.INTEGER(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.Column('colors', sa.TEXT(), nullable=False),
    sa.Column('desc', sa.TEXT(), nullable=False),
    sa.Column('pub_date', sa.DATETIME(), nullable=False),
    sa.Column('brand_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('image1', sa.VARCHAR(length=150), nullable=False),
    sa.Column('image2', sa.VARCHAR(length=150), nullable=False),
    sa.Column('image3', sa.VARCHAR(length=150), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
